<script setup lang="ts">
type Prediction = { id:string; contentId:string|null; prediction:string; confidence:number; status:string; model?:{id:string;name:string}|null; modelVersion?:{version:string}|null; createdAt:string };
type Evidence = { id:string; type:string; title:string|null; text:string|null; sourceUrl:string|null; fileName:string|null; fileUrl:string|null; createdAt:string; predictions?:Prediction[] };
type Investigation = { id:string; title:string; status:string; createdAt:string; analysisContents:Evidence[]; predictions:Prediction[] };
const config=useRuntimeConfig(); const api=String(config.public.apiBase||"");
const analyses=ref<Investigation[]>([]); const loading=ref(true); const error=ref("");
const selected=ref<{kind:string;label:string;detail:string}|null>(null);
async function load(){loading.value=true;error.value="";try{const r=await $fetch<{success:boolean;analyses:Investigation[];message?:string}>(`${api}/api/intelligence/graph`,{credentials:"include"});analyses.value=r.analyses||[]}catch(e:any){error.value=e?.data?.message||"Unable to load your evidence graph."}finally{loading.value=false}}
await load();
const rows=computed(()=>analyses.value.flatMap(a=>a.analysisContents.map((c,i)=>({a,c,p:a.predictions.find(x=>x.id&&(x as any).contentId===c.id)||null,y:100+i*100}))).slice(0,10));
const nodes=computed(()=>{
 const out:{id:string;kind:string;label:string;detail:string;x:number;y:number;data:any}[]=[];
 const addedModels=new Set<string>(); const addedSources=new Set<string>();
 analyses.value.slice(0,12).forEach((a,ai)=>out.push({id:a.id,kind:"Investigation",label:a.title,detail:`Status: ${a.status} ? Created ${new Date(a.createdAt).toLocaleString()}`,x:130,y:100+ai*120,data:a}));
 rows.value.forEach((r,i)=>{
  const y=100+i*100;
  out.push({id:r.c.id,kind:r.c.type,label:r.c.title||`${r.c.type} evidence`,detail:r.c.type==="TEXT"?`${(r.c.text||"").length} characters`:r.c.type==="SOURCE"?(r.c.sourceUrl||"Source URL"):r.c.fileName||"Image evidence",x:480,y,data:r.c});
  if(r.p){out.push({id:r.p.id,kind:"Prediction",label:r.p.prediction,detail:`${Math.round(r.p.confidence*100)}% confidence ? ${r.p.status} ? ${r.p.model?.name||"No model association"}`,x:810,y,data:r.p});if(r.p.model&&!addedModels.has(r.p.model.id)){addedModels.add(r.p.model.id);out.push({id:r.p.model.id,kind:"Model",label:r.p.model.name,detail:`Model version ${r.p.modelVersion?.version||"not recorded"}`,x:1120,y,data:r.p.model});}}
  if(r.c.sourceUrl&&!addedSources.has(r.c.sourceUrl)){addedSources.add(r.c.sourceUrl);let host=r.c.sourceUrl;try{host=new URL(host).hostname}catch{}out.push({id:`source:${r.c.sourceUrl}`,kind:"Source",label:host,detail:r.c.sourceUrl,x:1120,y:y+35,data:r.c});}
 });
 return out;
});
const edges=computed(()=>rows.value.flatMap(r=>{const e:any[]=[{from:r.a.id,to:r.c.id}];const p=r.a.predictions.find(x=>x.contentId===r.c.id);if(p){e.push({from:r.c.id,to:p.id});if(p.model)e.push({from:p.id,to:p.model.id});}if(r.c.sourceUrl)e.push({from:r.c.id,to:`source:${r.c.sourceUrl}`});return e}));
function point(id:string){return nodes.value.find(n=>n.id===id)}
function choose(n:any){selected.value={kind:n.kind,label:n.label,detail:n.detail}}
</script>
<template><main class="mx-auto max-w-7xl space-y-6 p-5 sm:p-8"><div class="mb-4"><DashboardBackToDashboard /></div><DashboardNav/><header><p class="text-xs font-semibold uppercase tracking-widest text-[var(--vl-sage-dark)]">Evidence intelligence</p><h1 class="mt-2 text-3xl font-semibold">Knowledge graph</h1><p class="mt-2 text-sm text-[var(--vl-muted)]">Relationships from your investigations, evidence, predictions, and registered models.</p></header><div v-if="loading" class="rounded-2xl bg-white/60 p-8">Loading graph…</div><div v-else-if="error" class="rounded-2xl border border-red-200 p-6 text-red-800">{{error}} <button class="ml-3 underline" @click="load">Retry</button></div><div v-else-if="!nodes.length" class="rounded-2xl border border-dashed p-10 text-center text-[var(--vl-muted)]">No investigations or evidence to graph yet.</div><template v-else><div class="overflow-x-auto rounded-3xl border border-[var(--vl-border)] bg-white/70 p-5"><svg viewBox="0 0 1320 1600" class="min-w-[1100px] w-full" role="img" aria-label="Interactive investigation relationship graph"><g stroke="#9aaa91" stroke-width="2" opacity=".65"><line v-for="edge in edges" :key="edge.from+edge.to" :x1="(point(edge.from)?.x||0)+120" :y1="point(edge.from)?.y||0" :x2="point(edge.to)?.x||0" :y2="point(edge.to)?.y||0"/></g><g v-for="node in nodes" :key="node.id" class="cursor-pointer" @click="choose(node)"><rect :x="node.x-110" :y="node.y-27" width="220" height="54" rx="14" :fill="node.kind==='Investigation'?'#e8ece2':node.kind==='Prediction'?'#f2eadb':'#faf8f2'" stroke="#cdd4c6"/><text :x="node.x" :y="node.y-2" text-anchor="middle" font-size="12" font-weight="700" fill="#292e28">{{node.label.slice(0,27)}}</text><text :x="node.x" :y="node.y+15" text-anchor="middle" font-size="10" fill="#687163">{{node.kind}}</text></g></svg></div><div class="grid gap-4 sm:grid-cols-2"><section class="rounded-2xl border border-[var(--vl-border)] bg-white/70 p-5"><h2 class="font-semibold">Node types</h2><p class="mt-2 text-sm text-[var(--vl-muted)]">Investigation ? evidence ? prediction ? model. Source evidence links to its recorded URL host. Nodes appear only when matching records exist.</p><div class="mt-4 flex flex-wrap gap-2"><button v-for="n in nodes" :key="n.id" class="rounded-full bg-[#f3f1e8] px-3 py-2 text-xs" @click="choose(n)">{{n.kind}} · {{n.label.slice(0,22)}}</button></div></section><section class="rounded-2xl border border-[var(--vl-border)] bg-white/70 p-5"><h2 class="font-semibold">Selected node</h2><template v-if="selected"><p class="mt-3 text-xs uppercase tracking-widest text-[var(--vl-muted)]">{{selected.kind}}</p><p class="mt-1 font-semibold">{{selected.label}}</p><p class="mt-2 text-sm text-[var(--vl-muted)]">{{selected.detail}}</p></template><p v-else class="mt-3 text-sm text-[var(--vl-muted)]">Select a node to inspect its information.</p></section></div></template></main></template>

